name: kcroz
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
   sdk: ">=2.18.2 <3.0.0"

dependencies:
   flutter:
      sdk: flutter

   cupertino_icons: ^1.0.2
   get:
   firebase_auth: ^4.2.8
   firebase_core: ^2.6.1
   google_sign_in:
   google_fonts: ^4.0.3

dev_dependencies:
   flutter_test:
      sdk: flutter

   flutter_lints: ^2.0.0

flutter:
   uses-material-design: true

   assets:
      - img/
      - assets/images/
