name: kcroz
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icon Packages
  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  # State Management
  get: ^4.6.5

  # Firebase Packages
  firebase_core: ^2.6.1
  firebase_auth: ^4.2.8
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.0

  # OnBoarding Packages
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.1

  #OTP Text Field Package
  flutter_otp_text_field: ^1.1.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  image_picker: ^0.8.7
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - img/
    - assets/images/splash_screen/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/on_boarding_images/on-boarding-image-1.jpg
    - assets/images/welcome_images/welcome-screen-image.png
    - assets/images/splash_screen/splash-screen-bottom.jpg
    - assets/logo/
    - assets/images/forget_password/
