// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq8J1I7jbqkrohBoRcDKfc5WmJwzjLCR4',
    appId: '1:1019076583860:web:124d82684b45adf626d2e1',
    messagingSenderId: '1019076583860',
    projectId: 'kcroz-app',
    authDomain: 'kcroz-app.firebaseapp.com',
    storageBucket: 'kcroz-app.appspot.com',
    measurementId: 'G-P1MN8JTW62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUlnksK8AGux-IBF8MU50gb72s5uKzfas',
    appId: '1:1019076583860:android:5d425def51d232b226d2e1',
    messagingSenderId: '1019076583860',
    projectId: 'kcroz-app',
    storageBucket: 'kcroz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSTLLmwZmI3wEWWdqwnjbDYDpDTvxvD_w',
    appId: '1:1019076583860:ios:480f041a9717880c26d2e1',
    messagingSenderId: '1019076583860',
    projectId: 'kcroz-app',
    storageBucket: 'kcroz-app.appspot.com',
    iosClientId: '1019076583860-knptgam5ciskr0qepecnq6k4csd4d2i4.apps.googleusercontent.com',
    iosBundleId: 'com.app.kcroz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSTLLmwZmI3wEWWdqwnjbDYDpDTvxvD_w',
    appId: '1:1019076583860:ios:ee0abf01d764e83826d2e1',
    messagingSenderId: '1019076583860',
    projectId: 'kcroz-app',
    storageBucket: 'kcroz-app.appspot.com',
    iosClientId: '1019076583860-9tq0fm689bg8qevf3nr0up2uiahp7ucq.apps.googleusercontent.com',
    iosBundleId: 'com.kcroz.kcroz',
  );
}
