// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGY--BCxHPgHD40CyFi3W8zSb00dOEei8',
    appId: '1:814801737668:android:da0c5189a9cbaacf77f691',
    messagingSenderId: '814801737668',
    projectId: 'fir-kcroz',
    storageBucket: 'fir-kcroz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvoduS32CZR1xouGujwB4VQ2_v2ZYAqr4',
    appId: '1:814801737668:ios:497bf4f9f86d203a77f691',
    messagingSenderId: '814801737668',
    projectId: 'fir-kcroz',
    storageBucket: 'fir-kcroz.appspot.com',
    androidClientId: '814801737668-jv91975e37tg2rbl76723hbhrbfld3cq.apps.googleusercontent.com',
    iosClientId: '814801737668-mbs0kiin3bcl0b21v9afknkbj88kirvf.apps.googleusercontent.com',
    iosBundleId: 'com.kcroz.app.db.kcroz',
  );
}
